openapi: 3.0.0
info:
  title: OHarvest
  description: Api of Oharvest
  version: 1.0.0

tags:
  - name: product
    description: Route related to the product
  - name: category
    description: Route related to the category
  - name: plot
    description: Route related to the plot
  - name: variety
    description: Route related to the variety

components:
  schemas:
    Category:
      title: Category
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: LÃ©gumes
    Plot:
      title: Plot
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: Parcelle 1
    Product:
      title: Product
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: Tomates
        isAvailable:
          type: boolean
          example: false
        image:
          type: string
          example: 'tomates.png'
        description:
          type: string
          example: Lorem ipsum
        tip:
          type: string
          example: Loremp ipsum
        harvestBeginAt:
          type: int
          example: 1
        harvestEndAt:
          type: int
          example: 12
        category:
          $ref: '#/components/schemas/Category'
        variety:
          $ref: '#/components/schemas/Variety'
    ProductInPlot:
      title: Product in plot
      type: object
      properties:
        plotId:
          type: number
          example: 1
        products:
          type: array
          items: 
            $ref: '#/components/schemas/Product'
    Variety:
      title: Variety
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: Jonagored
        harvestBeginAt:
          type: int
          example: 1
        harvestEndAt:
          type: int
          example: 12

paths:
  /api/categories:
    get:
      description: Return a list with all categories
      tags:
        - category
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Category'

  /api/categories/{id}:
    parameters:
      - name: id
        in: path
        description: ID of a category
        required: true
        schema:
          type: integer
    get:
      description: Return one categoy
      tags:
        - category
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Category'

  /api/products:
    get:
      description: Return a list with all products
      tags:
        - product
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'

  /api/products/available:
    get:
      description: Return a list with all products which are available
      tags:
        - product
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'

  /api/products/{id}:
    parameters:
      - name: id
        in: path
        description: ID of a product
        required: true
        schema:
          type: integer
    get:
      description: Return one product
      tags:
        - product
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'

  /api/plots:
    get:
      description: Return a list with all plots
      tags:
        - plot
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Plot'
  /api/plots/products:
    get:
      description: Return a list with all plots with their associated products
      tags:
        - plot
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/ProductInPlot'

  /api/plots/{id}:
    parameters:
      - name: id
        in: path
        description: ID of a plot
        required: true
        schema:
          type: integer
    get:
      description: Return one plot
      tags:
        - plot
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Plot'

  /api/varieties:
    get:
      description: Return a list with all varieties
      tags:
        - variety
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Variety'

  /api/varieties/{id}:
    parameters:
      - name: id
        in: path
        description: ID of a variety
        required: true
        schema:
          type: integer
    get:
      description: Return one variety
      tags:
        - variety
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Variety'